Release sysfsutils 2.1.0+repack-3

diff --git a/debian/sysfsutils.init b/debian/sysfsutils.init
--- a/debian/sysfsutils.init
+++ b/debian/sysfsutils.init
@@ -18,47 +18,56 @@
 # (c) 2005 Martin Pitt <mpitt@debian.org>
 
 CONFFILE=/etc/sysfs.conf
+CONFDIR=/etc/sysfs.d
 
-[ -r "$CONFFILE" ] || exit 0
+[ -r "$CONFFILE" -o -d "$CONFDIR" ] || exit 0
 
 . /lib/lsb/init-functions
+
+load_conffile() {
+    FILE="$1"
+    sed  's/#.*$//; /^[[:space:]]*$/d; 
+	  s/^[[:space:]]*\([^=[:space:]]*\)[[:space:]]*\([^=[:space:]]*\)[[:space:]]*=[[:space:]]*\(.*\)/\1 \2 \3/' \
+	  $FILE | {
+	while read f1 f2 f3; do
+	    if [ "$f1" = "mode" -a -n "$f2" -a -n "$f3" ]; then
+		if [ -f "/sys/$f2" ] || [ -d "/sys/$f2" ]; then
+		    chmod "$f3" "/sys/$f2"
+		else
+		    log_failure_msg "unknown attribute $f2"
+		fi
+	    elif [ "$f1" = "owner" -a -n "$f2" -a -n "$f3" ]; then
+		if [ -f "/sys/$f2" ]; then
+		    chown "$f3" "/sys/$f2"
+		else
+		    log_failure_msg "unknown attribute $f2"
+		fi
+	    elif [ "$f1" -a -n "$f2" -a -z "$f3" ]; then
+		if [ -f "/sys/$f1" ]; then
+		    # Some fields need a terminating newline, others
+		    # need the terminating newline to be absent :-(
+		     echo -n "$f2" > "/sys/$f1" 2>/dev/null ||
+			echo "$f2" > "/sys/$f1"
+		else
+		    log_failure_msg "unknown attribute $f1"
+		fi
+	    else
+		log_failure_msg "syntax error in $CONFFILE: '$f1' '$f2' '$f3'"
+		log_end_msg 1
+		exit 1
+	    fi
+	done
+    }
+}
 
 case "$1" in
     start|restart|force-reload)
 	log_begin_msg "Setting sysfs variables..."
 
-	sed  's/#.*$//; /^[[:space:]]*$/d; 
-              s/^[[:space:]]*\([^=[:space:]]*\)[[:space:]]*\([^=[:space:]]*\)[[:space:]]*=[[:space:]]*\(.*\)/\1 \2 \3/' \
-              $CONFFILE | {
-	    while read f1 f2 f3; do
-                if [ "$f1" = "mode" -a -n "$f2" -a -n "$f3" ]; then
-                    if [ -f "/sys/$f2" ] || [ -d "/sys/$f2" ]; then
-                        chmod "$f3" "/sys/$f2"
-                    else
-                        log_failure_msg "unknown attribute $f2"
-                    fi
-                elif [ "$f1" = "owner" -a -n "$f2" -a -n "$f3" ]; then
-                    if [ -f "/sys/$f2" ]; then
-                        chown "$f3" "/sys/$f2"
-                    else
-                        log_failure_msg "unknown attribute $f2"
-                    fi
-                elif [ "$f1" -a -n "$f2" -a -z "$f3" ]; then
-                    if [ -f "/sys/$f1" ]; then
-                        # Some fields need a terminating newline, others
-                        # need the terminating newline to be absent :-(
-                         echo -n "$f2" > "/sys/$f1" 2>/dev/null ||
-                            echo "$f2" > "/sys/$f1"
-                    else
-                        log_failure_msg "unknown attribute $f1"
-                    fi
-                else
-                    log_failure_msg "syntax error in $CONFFILE: '$f1' '$f2' '$f3'"
-                    log_end_msg 1
-                    exit 1
-                fi
-	    done
-	}
+	for file in $CONFFILE $CONFDIR/*.conf; do
+	    [ -r "$file" ] || continue
+	    load_conffile "$file"
+	done
 
 	log_end_msg 0
 	;;
